services:
  web:
    image: nginx:alpine
    restart: always
    networks:
      - n8n_default
    labels:
      - traefik.enable=true
      - traefik.docker.network=n8n_default
      - "traefik.http.routers.grad.rule=Host(`grad.iconstudio.tech`)"
      - traefik.http.routers.grad.entrypoints=web,websecure
      - traefik.http.routers.grad.tls=true
      - traefik.http.routers.grad.tls.certresolver=mytlschallenge
      - traefik.http.services.grad.loadbalancer.server.port=80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./dashboard.html:/usr/share/nginx/html/dashboard.html:ro
      - ./presentation.html:/usr/share/nginx/html/presentation.html:ro
      - ./data:/usr/share/nginx/html/data:ro

networks:
  n8n_default:
    external: true
